<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/15 11:15:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=share3d',
  'username' => 'root',
  'password' => 'test',
  'name' => 'doctrine',
)),);
